name: AutismCore
main: org.notleksa.autismcore.AutismCore
version: 0.1.2
api-version: 1.21
description: autism core real
author: NotLeksa

commands:
  core:
    description: Gives info about AutismCore
    usage: /core
    aliases: [autism, autismcore]
  hide:
    description: Hides players
    usage: /hide <all|staff|host|off>
  mutechat:
    description: Toggles chat mute
    usage: /mutechat
    permission: autismcore.mutechat
  spawn:
    description: Teleport to spawn
    usage: /spawn
  setspawn:
    description: Set the spawn location
    usage: /setspawn
    permission: autismcore.setspawn
  timer:
    description: Starts a timer
    usage: /timer <time|cancel> <minutes|seconds>
    permission: autismcore.timer
  invsee:
    description: Starts a timer
    usage: /invsee <player>
    permission: autismcore.invsee
  revive:
    description: Revives a player
    usage: /invsee <player>
    permission: autismcore.revive
    aliases: [rev]
  list:
    description: Lists all alive/dead players
    usage: /list <alive|dead>
  userevive:
    description: Request a revive using a revive token
    aliases: [userev]
  reviveaccept:
    description: Accept a player's revive request
    aliases: [revaccept]
  addrevive:
    description: Give a player revive tokens
    aliases: [addrev]
    permission: autismcore.addrevive
  tokens:
    description: Give a player revive tokens
    aliases: [revives, revtokens]
    permission: autismcore.addrevive
  gamble:
    description: Allows a player to gamble their revive tokens
    aliases: [tokengamble, gambletokens]
    permission: autismcore.tokengamble
  setcooldown:
    description: Sets the cooldown for a command
    aliases: [tokengamble, gambletokens]
    permission: autismcore.setcooldown

permissions:
  autismcore.chatbypass:
    description: Allows the user to speak when chat is muted
    default: op
  autismcore.mutechat:
    description: Allows the user to mute chat
    default: op
  autismcore.host:
    description: Makes the user a host
    default: op
  autismcore.staff:
    description: Makes the user staff
    default: op
  autismcore.setspawn:
    description: Allows the user to set the spawn location
    default: op
  autismcore.invsee:
    description: Allows the user to use /invsee
    default: op
  autismcore.timer:
    description: Allows the user to use /timer
    default: op
  autismcore.revive:
    description: Allows the user to use /revive
    default: op
  autismcore.addrevive:
    description: Allows the user to use /addrevive
    default: op
  autismcore.tokengamble:
    description: Allows the user to use /gamble
  autismcore.setcooldown:
    description: Allows the user to set command
    default: op